# Generated by Django 2.0.7 on 2018-07-17 11:35

from django.db import migrations
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', members.models.UserManager()),
            ],
        ),
    ]
